<?php
$molotovlogin = "molotovemailfreeaccount@example.com";
$molotovpassword = "molotovpassword";
header('content-type: audio/x-mpegurl');
header('Content-Disposition: inline; filename="fr-kodi.m3u"');
$useragent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:144.0) Gecko/20100101 Firefox/144.0";
$date = date("Ymd");
$ch1 = curl_init();
curl_setopt($ch1, CURLOPT_URL, "https://fapi.molotov.tv/v3.1/auth/login");
curl_setopt($ch1, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch1, CURLOPT_HEADER, 0);
curl_setopt($ch1, CURLOPT_USERAGENT, $useragent);
curl_setopt($ch1,CURLOPT_SSL_VERIFYPEER, false);
$hdrs1[]="User-Agent: " . $useragent;
$hdrs1[]="Accept: application/json";
$hdrs1[]="Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3";
$hdrs1[]="Content-type: application/json";
$hdrs1[]='X-Molotov-Agent: {"app_id":"browser_app","app_build":4,"app_version_name":"4.4.4","browser_name":"unknown","type":"desktop","os_version":"5.0 (X11)","electron_version":"0.0.0","os":"Linux x86_64","manufacturer":"","serial":"8a24ee77-571b-4500-ab24-4b0fff330dbb","model":"Firefox - Linux","hasTouchbar":false,"brand":"X11; Linux x86_64; rv:144.0","api_version":8,"features_supported":["social","new_button_conversion","paywall","channel_separator","empty_view_v2","store_offer_v2","player_mplus_teasing","embedded_player","channels_classification","new-post-registration","appstart-d0-full-image","payment_v2","armageddon","user_favorite","parental_control_v3","emptyview_v2","before_pay_periodicity_selection","player_midrolls","cookie_wall","reverse_epg"],"inner_app_version_name":"5.7.0","qa":false}';
$hdrs1[]="Origin: https://app.molotov.tv";
$hdrs1[]="Referer: https://app.molotov.tv/";
curl_setopt($ch1, CURLOPT_HTTPHEADER, $hdrs1);
$post = '{"grant_type":"password","email":"' . $molotovlogin . '","password":"' . $molotovpassword . '"}';
curl_setopt($ch1, CURLOPT_POSTFIELDS, $post);
$res1 = curl_exec($ch1);
curl_close($ch1);
$json1 = json_decode($res1, true);
$accesstoken = $json1["auth"]["access_token"];
$ch2 = curl_init();
curl_setopt($ch2, CURLOPT_URL, "https://fapi.molotov.tv/v2/me/assets?id=19&source=embedded-player&trkCp=player&trkOcr=2&trkOp=channel_home&trkOs=player-embedded&trkOsp=1&type=channel&position=NaN&start_over=false&embedded=true&skip_dialogs=true&access_token=" . $accesstoken . "");
curl_setopt($ch2, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch2, CURLOPT_HEADER, 0);
curl_setopt($ch2, CURLOPT_USERAGENT, $useragent);
curl_setopt($ch2,CURLOPT_SSL_VERIFYPEER, false);
$hdrs2[]="User-Agent: " . $useragent;
$hdrs2[]="Accept: application/json";
$hdrs2[]="Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3";
$hdrs2[]="Content-type: application/json";
$hdrs2[]='X-Molotov-Agent: {"app_id":"browser_app","app_build":4,"app_version_name":"4.4.4","browser_name":"unknown","type":"desktop","os_version":"5.0 (X11)","electron_version":"0.0.0","os":"Linux x86_64","manufacturer":"","serial":"8a24ee77-571b-4500-ab24-4b0fff330dbb","model":"Firefox - Linux","hasTouchbar":false,"brand":"X11; Linux x86_64; rv:144.0","api_version":8,"features_supported":["social","new_button_conversion","paywall","channel_separator","empty_view_v2","store_offer_v2","player_mplus_teasing","embedded_player","channels_classification","new-post-registration","appstart-d0-full-image","payment_v2","armageddon","user_favorite","parental_control_v3","emptyview_v2","before_pay_periodicity_selection","player_midrolls","cookie_wall","reverse_epg"],"inner_app_version_name":"5.7.0","qa":false}';
$hdrs2[]="X-Tcf-String: CQaDXoAQaDXoAAHABBENCEFsAP_gAEPgAAqILPkB7C7ebSlhYTx1IPsEGYgO0UAS4EAgBACJAygBgApEsJQEwGAgIATAAIAKGQIAIHBBAQBlAADEBUCAYAAEICDEAAAAgRAIIiBAAAEBAkBACABBEwAAEACQgAAREAUAmAIAAVrkAUBgAgAABEAAoAAAAIABAAOAAAAgAAIQAQAIAigACAAAAAIAEAEEAFAAAAAAAAECAAAAAAAUABAAQBAAACAAAAAAAgAAgAQAAAAAAAAAAAgqXBQAAWAA8ACoAFwAOAAeABAACQAFQALwAZQA0ADUAHAAPAAjgBMACgAFWALgAugBiADQAG8APwAhABDACWAE4AK0AYYAygBmgDRAHeAPgAfYA_QCEAEUAItARwBHQCSgFXALEAYoAz4BogDXgG0ANwAcQA6gB7QD7AImAReAj0BIgCYgEyAJpAU0ArsBeYC-gGLAMqAZYA00BrADiwHigP3Af2BAECHIEdgJVgTOAm8BUsAA.f_wACHwAAAAA";
$hdrs2[]="Origin: https://app.molotov.tv";
$hdrs2[]="Referer: https://app.molotov.tv/";
curl_setopt($ch2, CURLOPT_HTTPHEADER, $hdrs2);
$res2 = curl_exec($ch2);
curl_close($ch2);
$json2 = json_decode($res2, true);
$molotovsing = $json2["stream"]["suffix_url"];
$molotovsing = str_replace("/v1/dash/adbdb0be988e4727447cd4c469e80a63f5b23bff/mtv-ftv-france2-dash-prod/public/france2/france2.isml/hdreadyshft.mpd?", "", $molotovsing);
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, "https://andykimpe1.github.io/iptv/playlist/fr-kodi-test.m3u");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_HEADER, 0);
curl_setopt($ch, CURLOPT_USERAGENT, $useragent);
curl_setopt($ch,CURLOPT_SSL_VERIFYPEER, false);
$hdrs[]="User-Agent: " . $useragent; 
curl_setopt($ch, CURLOPT_HTTPHEADER, $hdrs);
$res = curl_exec($ch);
curl_close($ch);
$res = str_replace("MOLOTOSIGN", $molotovsing, $res);
$res = str_replace("USERAGENT", $useragent, $res);
$res = str_replace("DATE", $date, $res);
echo $res;
?>
