<?php
header('content-type: audio/x-mpegurl');
header('Content-Disposition: inline; filename="fr-kodi.m3u"');
//$molotovsing = "signature=20251112050000_17ec504bb50f2097ea5be12de027e8da3c15449e";
$useragent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:144.0) Gecko/20100101 Firefox/144.0";
$date = date("Ymd");
$ch1 = curl_init();
curl_setopt($ch1, CURLOPT_URL, "https://fapi.molotov.tv/v2/me/assets?id=19&source=embedded-player&trkCp=player&trkOcr=2&trkOp=channel_home&trkOs=player-embedded&trkOsp=1&type=channel&position=NaN&start_over=false&embedded=true&skip_dialogs=true&access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50X2lkIjoiOTYyMjQxIiwiYWxsb3dlZF9jaWRycyI6WyIwLjAuMC4wLzAiXSwiZXhwaXJlcyI6MTc2Mjc5MDQ4MywicHJvZmlsZV9pZCI6Ijk2MzUzMyIsInNjb3BlcyI6bnVsbCwidXNlcl9pZCI6Ijk2MjI0MSIsInYiOjF9.ZnGY9WQp0rkjsCFyTJfnicEz0OFwYvW30FdlbnhSgrc");
curl_setopt($ch1, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch1, CURLOPT_HEADER, 0);
curl_setopt($ch1, CURLOPT_USERAGENT, $useragent);
curl_setopt($ch1,CURLOPT_SSL_VERIFYPEER, false);
$hdrs1[]="User-Agent: " . $useragent;
$hdrs1[]="Accept: application/json";
$hdrs1[]="Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3";
$hdrs1[]="Content-type: application/json";
$hdrs1[]='X-Molotov-Agent: {"app_id":"browser_app","app_build":4,"app_version_name":"4.4.4","browser_name":"unknown","type":"desktop","os_version":"5.0 (X11)","electron_version":"0.0.0","os":"Linux x86_64","manufacturer":"","serial":"8a24ee77-571b-4500-ab24-4b0fff330dbb","model":"Firefox - Linux","hasTouchbar":false,"brand":"X11; Linux x86_64; rv:144.0","api_version":8,"features_supported":["social","new_button_conversion","paywall","channel_separator","empty_view_v2","store_offer_v2","player_mplus_teasing","embedded_player","channels_classification","new-post-registration","appstart-d0-full-image","payment_v2","armageddon","user_favorite","parental_control_v3","emptyview_v2","before_pay_periodicity_selection","player_midrolls","cookie_wall","reverse_epg"],"inner_app_version_name":"5.7.0","qa":false}';
$hdrs1[]="X-Tcf-String: CQaDXoAQaDXoAAHABBENCEFsAP_gAEPgAAqILPkB7C7ebSlhYTx1IPsEGYgO0UAS4EAgBACJAygBgApEsJQEwGAgIATAAIAKGQIAIHBBAQBlAADEBUCAYAAEICDEAAAAgRAIIiBAAAEBAkBACABBEwAAEACQgAAREAUAmAIAAVrkAUBgAgAABEAAoAAAAIABAAOAAAAgAAIQAQAIAigACAAAAAIAEAEEAFAAAAAAAAECAAAAAAAUABAAQBAAACAAAAAAAgAAgAQAAAAAAAAAAAgqXBQAAWAA8ACoAFwAOAAeABAACQAFQALwAZQA0ADUAHAAPAAjgBMACgAFWALgAugBiADQAG8APwAhABDACWAE4AK0AYYAygBmgDRAHeAPgAfYA_QCEAEUAItARwBHQCSgFXALEAYoAz4BogDXgG0ANwAcQA6gB7QD7AImAReAj0BIgCYgEyAJpAU0ArsBeYC-gGLAMqAZYA00BrADiwHigP3Af2BAECHIEdgJVgTOAm8BUsAA.f_wACHwAAAAA";
$hdrs1[]="Origin: https://app.molotov.tv";
$hdrs1[]="Referer: https://app.molotov.tv/";
curl_setopt($ch1, CURLOPT_HTTPHEADER, $hdrs1);
$res1 = curl_exec($ch1);
curl_close($ch1);
//echo $res1;
//var_dump(json_decode($res1, true));
$json = json_decode($res1, true);
$finaljson = $json["stream"]["suffix_url"];
$finaljson = str_replace("/v1/dash/adbdb0be988e4727447cd4c469e80a63f5b23bff/mtv-ftv-france2-dash-prod/public/france2/france2.isml/hdreadyshft.mpd?", "", $finaljson);
$molotovsing =  $finaljson;
//exit;
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, "https://andykimpe1.github.io/iptv/playlist/fr-kodi-test.m3u");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_HEADER, 0);
curl_setopt($ch, CURLOPT_USERAGENT, $useragent);
curl_setopt($ch,CURLOPT_SSL_VERIFYPEER, false);
$hdrs[]="User-Agent: " . $useragent; 
curl_setopt($ch, CURLOPT_HTTPHEADER, $hdrs);
$res = curl_exec($ch);
curl_close($ch);
$res = str_replace("MOLOTOSIGN", $molotovsing, $res);
$res = str_replace("USERAGENT", $useragent, $res);
$res = str_replace("DATE", $date, $res);
echo $res;
?>
