<?php
$ch2 = curl_init();
curl_setopt($ch2, CURLOPT_URL, "https://raw.githubusercontent.com/Paradise-91/ParaTV/main/streams/tf1plus/tf1.m3u8");
curl_setopt($ch2, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch2, CURLOPT_HEADER, 0);
curl_setopt($ch2, CURLOPT_USERAGENT, "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:139.0) Gecko/20100101 Firefox/139.0");
curl_setopt($ch2,CURLOPT_SSL_VERIFYPEER, false);
$res2 = curl_exec($ch2);
curl_close($ch2);
$res2 = str_replace("https://", "url=\"https://", $res2);
$res2 = str_replace("index_1.m3u8", "\"", $res2);
preg_match_all('#url="(.*?)"#', $res2, $match);
$match = $match[1][0];
echo "#EXTM3U\r\n";
echo "#EXT-X-VERSION:6\r\n";
echo "#EXT-X-INDEPENDENT-SEGMENTS\r\n";
echo "\r\n";
echo "# variants\r\n";
echo "#EXT-X-STREAM-INF:BANDWIDTH=3192758,AVERAGE-BANDWIDTH=2890952,RESOLUTION=1280x720,FRAME-RATE=25,CODECS=\"avc1.4D401F,mp4a.40.2\",SUBTITLES=\"subtitles\",AUDIO=\"audio_0\"\r\n";
echo "" . $match . "index_1.m3u8\r\n";
//echo "#EXT-X-STREAM-INF:BANDWIDTH=2207158,AVERAGE-BANDWIDTH=2010952,RESOLUTION=1024x576,FRAME-RATE=25,CODECS=\"avc1.4D401F,mp4a.40.2\",SUBTITLES=\"subtitles\",AUDIO=\"audio_0\"\r\n";
//echo "" . $match . "index_2.m3u8\r\n";
//echo "#EXT-X-STREAM-INF:BANDWIDTH=1591189,AVERAGE-BANDWIDTH=1460988,RESOLUTION=1024x576,FRAME-RATE=25,CODECS=\"avc1.4D401F,mp4a.40.2\",SUBTITLES=\"subtitles\",AUDIO=\"audio_0\"\r\n";
//echo "" . $match . "index_3.m3u8\r\n";
echo "\r\n";
echo "# media\r\n";
echo "#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID=\"audio_0\",CHANNELS=\"2\",NAME=\"fra\",LANGUAGE=\"fra\",DEFAULT=YES,AUTOSELECT=YES,URI=\"" . $match . "index_12_0.m3u8\"\r\n";
//echo "#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID=\"audio_0\",CHANNELS=\"2\",NAME=\"mul\",LANGUAGE=\"mul\",DEFAULT=NO,AUTOSELECT=NO,URI=\"" . $match . "index_13_0.m3u8\"\r\n";
//echo "#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID=\"audio_0\",CHANNELS=\"2\",NAME=\"sme\",LANGUAGE=\"sme\",DEFAULT=NO,AUTOSELECT=NO,URI=\"" . $match . "index_14_0.m3u8\"\r\n";
//echo "#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID=\"subtitles\",NAME=\"no subtitles\",DEFAULT=YES,AUTOSELECT=YES,FORCED=NO,LANGUAGE=\"mul\",URI=\"" . $match . "index_9_0.m3u8\"\r\n";
//echo "#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID=\"subtitles\",NAME=\"Sourds et malentendant\",DEFAULT=NO,AUTOSELECT=NO,FORCED=NO,LANGUAGE=\"sme\",URI=\"" . $match . "index_10_0.m3u8\"\r\n";
echo "#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID=\"subtitles\",NAME=\"français\",DEFAULT=YES,AUTOSELECT=YES,FORCED=YES,LANGUAGE=\"fra\",URI=\"" . $match . "index_11_0.m3u8\"\r\n";
header('Content-Type: application/vnd.apple.mpegurl');
exit;
